kind: Service
apiVersion: v1
metadata:
  name: stable-app-service
  labels:
    monitored: "true"

spec:
  type: ClusterIP
  selector:
    app: stable-app-deployment
  ports:
    - name: http  
      port: 8000
      targetPort: 8000